modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All Rights Reserved"

[[mods]] #mandatory
# The modid of the mod
modId="mixedscavenger" #mandatory

version="1.0.0" #mandatory
# A display name for the mod
displayName="MixedScavenger" #mandatory

description='''
Мод на антидроп by lLuffy
'''
[[dependencies.MixedScavanger]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[36,)" #mandatory
   ordering="NONE"
   # Side this dependency is applied on - BOTH, CLIENT or SERVER
   side="SERVER"
[[dependencies.MixedScavenger]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
